version: "3"
services:
  frontend.mvc:
    build:
      context: Frontend.Mvc
      dockerfile: Dockerfile
    container_name: frontend.mvc
    image: houssemdocker/frontend.mvc:${TAG:-0.1}
    ports: 
      - 6100:80
    environment: 
      CatalogApiUrl: http://catalog.api
      BasketApiUrl: http://basket.api
    depends_on: 
      - catalog.api
      - catalog.db

  catalog.api:
    build:
      context: .
      dockerfile: Catalog.Api.Dockerfile
    container_name: catalog.api
    image: houssemdocker/catalog.api:${TAG:-0.1}
    ports:
      - 6200:80
    environment: 
      ConnectionStrings__CatalogContext: Server=catalog.db;Database=CatalogContext;User Id=sa;Password=@Aa123456
    depends_on:
      - catalog.db

  catalog.db:
    container_name: mssql-server-linux.catalog.db
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "@Aa123456"
      ACCEPT_EULA: "Y"

  basket.api:
    build:
      context: .
      dockerfile: Basket.Api.Dockerfile
    container_name: basket.api
    image: houssemdocker/basket.api:${TAG:-0.1}
    ports:
      - 6300:80
    environment: 
      ConnectionStrings__BasketContext: Server=basket.db;Database=BasketContext;User Id=sa;Password=@Aa123456
    depends_on:
      - basket.db

  basket.db:
    container_name: mssql-server-linux.basket.db
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "@Aa123456"
      ACCEPT_EULA: "Y"

  orders.webjob:
    build:
      context: .
      dockerfile: Orders.WebJob.Dockerfile
    container_name: orders.webjob
    image: houssemdocker/orders-webjob:${TAG:-0.1}
    ports:
      - 6400:80
    environment: 
      RabbitMqUri: "amqp://guest:guest@localhost:5672//" # "/" is the name of the virtual host in RabbitMQ
      ConnectionStrings__ServiceBusConnectionString: Endpoint=sb://microservicesoncontainers.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=pydtJlzPcGSoHLuO/YcUi6MDZ/liZRI7BTMiwP4glXA=
